### ISSUE TITLE
/group/ returns 500

### ISSUE THREAD

**Issue by PriceChild** [freenode/gms#100]
Registered user, logged into web ui and clicked "Your Groups": https://gms-test.freenode.net/group/

Returns 500 with no styling and the following content:

> (en) Please come back later
> (fr) SVP veuillez revenir plus tard
> (de) Bitte versuchen sie es spaeter nocheinmal
> (at) Konnten's bitt'schoen spaeter nochmal reinschauen
> (no) Vennligst prov igjen senere
> (dk) Venligst prov igen senere
> (pl) Prosze sprobowac pozniej
> (pt) Por favor volte mais tarde
> (ru) Попробуйте еще раз позже
> (ua) Спробуйте ще раз пізніше
> (it) Per favore riprova più tardi

**Comment by nhandler** [comment]
I was able to reproduce this issue yesterday following the same workflow.

**Comment by errietta** [comment]
Ah wait. Is this because you have no contact info

On Thu, Jan 7, 2016, 17:12 Nathan Handler <notifications@github.com> wrote:

> I was able to reproduce this issue yesterday following the same workflow.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/freenode/gms/issues/100#issuecomment-169734508>.
>
-- 
Errietta Kostala
<errietta@errietta.me>

**Comment by nhandler** [comment]
I didn't at the time. I was simply exploring the navigational buttons and going top to bottom, which led me to this page before the contact info one.

**Comment by errietta** [comment]
Alright then i already know what the problem is

On Thu, Jan 7, 2016, 17:27 Nathan Handler <notifications@github.com> wrote:

> I didn't at the time. I was simply exploring the navigational buttons and
> going top to bottom, which led me to this page before the contact info one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/freenode/gms/issues/100#issuecomment-169744850>.
>
-- 
Errietta Kostala
<errietta@errietta.me>
