### ISSUE TITLE
The cloak assignment interface is prone to abuse

### ISSUE THREAD

**Issue by mniip** [freenode/gms#118]
One can try to assign a million cloaks with one request, which would spam the gms channel, along with the user's inbox, as well as the database and the user interface.

**Comment by errietta** [comment]
I don't think GC's would purposely abuse it, but you still have a point. Perhaps send only one notice, e.g. X requested N cloaks?

**Comment by decontamin4t0R** [comment]
Would be the best. But maybe also try to limit the count of cloaks?

**Comment by errietta** [comment]
Let's just limit the amount of notices sent (1 per request rather than 1 per cloak ) for now

**Comment by christeld** [comment]
I am good with that for now!
