### ISSUE TITLE
GMS allows you to request identical cloaks on people.

### ISSUE THREAD

**Issue by KindOne-** [freenode/gms#119]
I have ```testing/lol``` and it let me request ```testing/lol``` for someone else.

**Comment by mistohise** [comment]
Duplicate cloaks are a feature, not a bug.

**Comment by mniip** [comment]
Even for the same user?

**Comment by mistohise** [comment]
Setting the same cloak on the same person is the same as doing nothing. All that is lost is a few cycles.

**Comment by mniip** [comment]
Yeah except that a new cloak change request is created, the person is notified over memoserv, a new entry appears under "your group cloaks", and subsequently in the staff review queue.

**Comment by mistohise** [comment]
One could then argue that there is a case for not accepting new requests for the same thing, but that's not what this bug was raised for..

**Comment by christeld** [comment]
We may want to make it do a "lol this user already has the given cloak set" type thing ala NS but otherwise a project should indeed be able to use a single cloak for all its members if that is what floats that particular boat! :)

**Comment by mniip** [comment]
It should probably also check requested cloaks too.
