### ISSUE TITLE
Incorrect memos

### ISSUE THREAD

**Issue by mistohise** [freenode/gms#120]
After rejecting a cloak or approving a cloak it seems to send a memo to me saying that "my request" was rejected/approved.  

Two things are : 1) I don't want such a memo in either event and
2) the memo is incorrect, it's not my request it's someone else's. 

So actually I suppose
3) the memo should be going elsewhere.

I'll leave this ticket as "please check that memos go to the correct recipient"

**Comment by mniip** [comment]
It sends a memo to the GC that requested the cloaks in first place. Is this not what should be happening?

**Comment by mistohise** [comment]
I can't easily re-test this as I can't get the admin screen to refresh, but I'm fairly sure that it also sends memos to the approving gms admin.

**Comment by mniip** [comment]
Ok I have re-tested this. It does indeed send a memo to the `changed_by` of the last active change, which in this case is the admin who put the change into an `approved` state.

**Comment by decontamin4t0R** [comment]
So... Get the changed_by before the state changes, or send the memo to all gc's? (With a proper message) or... Make a new field with something like requested_by ?

**Comment by errietta** [comment]
I'd get changed by before state changes

On Wed, 20 Jan 2016 06:01 decontamin4t0R <notifications@github.com> wrote:

> So... Get the changed_by before the state changes, or send the memo to all
> gc's? (With a proper message) or... Make a new field with something like
> requested_by ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/freenode/gms/issues/120#issuecomment-173101610>.
>
-- 
Errietta Kostala
<errietta@errietta.me>

**Comment by mniip** [comment]
Fixed in cae97189670f86bb935ec4038b3863f7a0ef51c7
