### ISSUE TITLE
Possibility to check group affiliation other than cloaks

### ISSUE THREAD

**Issue by Fuchs** [freenode/gms#136]
As a operator or user when talking to someone on freenode, i would like to be able to check that they do have a recognised affiliation with a group without having to rely on cloaks. 

Sample use case: a person might be affiliated with various groups, but only wears the cloak of one. I need to know whether that user is also affiliated with a different project.

Further reading: discussion in #freenode-gms, 2016/02/15, 22:15 UTC

**Comment by errietta** [comment]
Merged with #137
