### ISSUE TITLE
GMS-lite

### ISSUE THREAD

**Issue by christeld** [freenode/gms#143]
GRF-stylee form from GMS with an additional "account name" field (to later link to correct nickserv account for GMS administration) to use as an interim way of registration for groups while waiting for GMS proper. It'd need to e-mail a copy to projects@, plus have a little script that allows groupies to yay/nay and also save the data in a way that allows us to import the table to the GMS database come initial launch. 

This would save GCs from having to register twice (now and when GMS launches) and will hopefully allow us to process group registrations without losing momentum again as we wait for production GMS. 

Erry: most brief request above, refer to previous IRC conversation for additional context!

THANKEE PLEASE.

**Comment by christeld** [comment]
As GMS proper is due to launch in a month (hopefully testing ready very very soon?!) this is obviously no longer required.

**Comment by errietta** [comment]
Yes, **hopefully..**
(I'll get back to GMS as soon as I'm done screaming about this though)
![screenshot 2016-04-27 at 10 12 58](https://cloud.githubusercontent.com/assets/134585/14847470/a6e997ce-0c60-11e6-91a0-2a832ae8f81e.png)
