### ISSUE TITLE
Session token isn't regenerated on privilege change

### ISSUE THREAD

**Issue by spb** [freenode/gms#146]
The session token isn't regenerated on a privilege change, such as logging in or out. It should be.

**Comment by errietta** [comment]
@spb str please. I did the following:
* Log in
* Check token by looking at page source. Token was 8e71df26d8ebeb54cb01dd15eae641667adc5050
* Log out
* Check token by looking at page source. Token was b52cd9e30e11b8d308ad9368bd3ea03d39239fa7

It should indeed be destroyed on log out at least - logout calls :DestroyToken. So if it's somewhere else it should happen, where?

**Comment by errietta** [comment]
Should regenerate on log in apparently
