### ISSUE TITLE
Session cookie doesn't have the Secure flag

### ISSUE THREAD

**Issue by spb** [freenode/gms#147]
The gms_web_session cookie doesn't have the Secure flag set on it, which means it'll be transmitted in cleartext if the browser tries to open http://gmsurl/. Set the Secure flag on all cookies.

**Comment by tomaw** [comment]
There's a report that this is still an issue. erry, please investigate.

**Comment by shadowcat-mst** [comment]
Config's in the wrong place. @tomaw please remember to ask me to look at this stuff, the whole point of me being involved is I know somewhat more about this than the rest of the people involved.

Looks like the fix should be:

    diff --git a/lib/GMS/Web.pm b/lib/GMS/Web.pm
    index 0448b2c..9dc927d 100644
    --- a/lib/GMS/Web.pm
    +++ b/lib/GMS/Web.pm
    @@ -41,9 +41,10 @@ our $VERSION = '0.01';
     __PACKAGE__->config(
         name => 'GMS::Web',
     
    -    session => { flash_to_stash => 1 },
    -
    -    cookie_secure => 1,
    +    session => {
    +        flash_to_stash => 1,
    +        cookie_secure => 1,
    +    },
     
         default_view => 'TT',
     
Please verify and commit.

**Comment by errietta** [comment]
Fixed in https://github.com/freenode/gms/commit/cf8a69e621ce2166b61ab04db6ff36aed5ed8c8b
