### ISSUE TITLE
"Requested cloaks" should be updated when a SOPER changes a cloak manually

### ISSUE THREAD

**Issue by maxteufel** [freenode/gms#24]
When I request a cloak change as a GC and a services operator uses `/ns vhost` to add that cloak, the cloak is listed under both "Active cloaks" and "Requested cloaks".
![image1](https://cloud.githubusercontent.com/assets/6442985/4757289/486b6810-5ad4-11e4-9418-3c8cf47cb3cc.png)

**Comment by errietta** [comment]
Closed for now
