### ISSUE TITLE
Correct visibility of the "small blurb" field

### ISSUE THREAD

**Issue by Gryllida** [freenode/gms#31]
When I register a group, I see that the "small blurb" field is shown even if I don't want to add it to public group listing.

**Comment by mvy** [comment]
Private groups can still have a description, can't they? Especially if you can access this as a member of the group someday?

**Comment by christeld** [comment]
I am quite in favour of mvy's comment to leave the option open also to those choosing not to be listed on the website.

**Comment by errietta** [comment]
It's not a required field any way

On Sun, Feb 21, 2016 at 1:02 PM Christel Dahlskjaer <
notifications@github.com> wrote:

> I am quite in favour of mvy's comment to leave the option open also to
> those choosing not to be listed on the website.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/freenode/gms/issues/31#issuecomment-186819948>.
>
-- 
Errietta Kostala
<errietta@errietta.me>

**Comment by errietta** [comment]
The field isn't required, and it's not even used at this time. Let's close this, and we can make an issue on  a later milestone on what to do with said field
