### ISSUE TITLE
On /staff/search_namespaces/

### ISSUE THREAD

**Issue by ncoevoet** [freenode/gms#61]
There is a select box to search on cloaks, 
That doesn't work and always search on namespace, 
or the error message is incorrect :

Unable to find any namespaces that match your search criteria. Please try again.

**Comment by errietta** [comment]
You went on the search namespaces page, which searches cloak namespaces,
and not requested/applied cloaks - these are different things.

If you look for cloak /requests/, you want to 'search changes' and then
'search cloak changes'. If you want to look at applied cloaks, I assume you
can use listvhost/?

Please clarify if this doesn't answer your issue

**Comment by ncoevoet** [comment]
ok :)
