### ISSUE TITLE
/ allowed as sub cloak

### ISSUE THREAD

**Issue by errietta** [freenode/gms#75]
20:43 < *decontamin4t0R> i have one user assigned a cloak with gov// by gms... should that be possible? (locally)
20:44 < *decontamin4t0R> ive put a cloak change request with a sub-cloak /...

**Comment by mniip** [comment]
What's the issue with this exactly? I, for one, don't see anything wrong with a `foo//` cloak. If staff think such a cloak is inappropriate they can just reject it. Unlike other cloak restrictions this doesn't cause an error in NickServ's `VHOST`

**Comment by decontamin4t0R** [comment]
[16:21:14] <mniip> considering foo// plays nicely with services,
[16:21:23] <mniip> I don't see a reason why it'd be rejected
