### ISSUE TITLE
Arbitrary values allowed in group type.

### ISSUE THREAD

**Issue by mniip** [freenode/gms#81]
With simple browser console skills one can edit the HTML for the dropdown list and change the group type to an arbitrary string. This crashes the web frontend whenever the group type is to be displayed. It also results in an arbitrary string being passed to XMLRPC but fortunately it is too dumb to copy newlines into command arguments, preventing GMSServ from emitting arbitrary commands into the services->ircd link.

**Comment by decontamin4t0R** [comment]
As this is connected to the database, this is rather not an easy bug anymore. It's more a hard or middle hard bug.

**Comment by errietta** [comment]
https://github.com/freenode/gms/commit/d9baf9b6c621904459d06ea9315554d87a0b3330 should fix this after an upgrade (./bin/deploy.pl upgrade)
Could somebody write tests? :pray:
