### ISSUE TITLE
Editing pending groups

### ISSUE THREAD

**Issue by mniip** [freenode/gms#84]
The `/group/#/view` page doesn't include an 'Edit Group Information' link if the group is in pending state, as if implying that one shouldn't be allowed to do that. However one can still manually navigate to `/group/#/edit` and request a change, and such a change will work fine if approved.

**Comment by decontamin4t0R** [comment]
So what? Denying access to /edit or adding a link there?

**Comment by errietta** [comment]
If it doesn't break anything (I'd have to check) I'd say allowing people to
change info (in case they made a mistake) while pending approval may be sane

On Tue, Jan 5, 2016 at 7:19 PM decontamin4t0R <notifications@github.com>
wrote:

> So what? Denying access to /edit or adding a link there?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/freenode/gms/issues/84#issuecomment-169102498>.
>
-- 
Errietta Kostala
<errietta@errietta.me>

**Comment by nhandler** [comment]
I would like to see this feature as well. Otherwise, we will have people emailing the corrections to us, which is far from ideal.
