### ISSUE TITLE
rejected cloak namespaces sit in limbo and can't be approved or rejected (again)

### ISSUE THREAD

**Issue by mistohise** [freenode/gms#87]
Cloak namespaces that are rejected seem to sit around as ghosts.
see "moo" on testnet

**Comment by mistohise** [comment]
Possibly a sub-issue of #97

**Comment by decontamin4t0R** [comment]
I see this:
![temp](https://cloud.githubusercontent.com/assets/13054654/12372862/e2d7b086-bc65-11e5-91f2-b64d269a32aa.png)

**Comment by mistohise** [comment]
To answer erry's question from elsewhere : post-refresh.

**Comment by errietta** [comment]
This seems to be a problem when a group is deleted by their original contacts and registered by a new person.

**Comment by christeld** [comment]
Ideally I'd like a fix to this before v1. :)

**Comment by mniip** [comment]
Last time I tried to reproduce this I couldn't.

**Comment by errietta** [comment]
@mniip pretty sure this is the "new group takes over deleted" one bug, but we really need @mistohise  to confirm

**Comment by mistohise** [comment]
Still not fixed, but presenting differently

Submit a new group
Await approval of group
Submit a new cloak namespace request
   -- Admin rejects
Attempt to resubmit the same request

Receive error message stating
"Another group has requested that namespace. Are you sure you want to create a conflicting request?"

Tick button to force the "conflicting" request.

Request does not appear in admin view for approval.

**Comment by errietta** [comment]
@mistohise It'll show in pending namespace changes instead...

![screenshot 2016-06-06 at 19 34 53](https://cloud.githubusercontent.com/assets/134585/15833231/cb3a9790-2c1d-11e6-85aa-c9921e3ed5af.png)
