### ISSUE TITLE
Awaiting admin request helper numbers are wrong

### ISSUE THREAD

**Issue by mistohise** [freenode/gms#89]
The numbers that act as helpers on the admin requests are incorrectly showing how many requests are waiting. Some are too high and some too low.  Probably links with the ghost rejected requests issue.

**Comment by mistohise** [comment]
Example -
![exampleadmin](https://cloud.githubusercontent.com/assets/9051085/12155950/08cfbd22-b4c0-11e5-9f33-8eecb8e056ec.jpg)

**Comment by errietta** [comment]
@mistohise Did a1830cd2b004c4040ffc347028f1189348fd0715 fix this?
