### ISSUE TITLE
Contact name should not allow various special characters

### ISSUE THREAD

**Issue by mistohise** [freenode/gms#94]
Allowing characters like ^ in a contact name serves no real purpose.

**Comment by PriceChild** [comment]
Does the caret break anything?

I'd worry if we add some sort of non-technical limitation here we'll make an incorrect assumption?

http://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/

**Comment by mistohise** [comment]
It might be that it's safe programmatically but looks ugly from a UI perspective.

**Comment by PriceChild** [comment]
I'm worried more about correctness, rejecting valid names if restrictions are introduced.

**Comment by errietta** [comment]
+ on @PriceChild. We have to be careful to not accidentally not allow somebody to enter their name because it has some weird characters.

**Comment by mistohise** [comment]
What weird characters do we think that people would have?

**Comment by errietta** [comment]
We could have a black list of chars that names could never possibly have..
But I wonder if the possibility of problems is worth it.
Naméß from all over the wÖrld (世界) have diff3rent characters and writing
methodς.

On Sat, Jan 16, 2016 at 11:28 AM Dr Emenculous Paboory <
notifications@github.com> wrote:

> What weird characters do we think that people would have?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/freenode/gms/issues/94#issuecomment-172191661>.
>
-- 
Errietta Kostala
<errietta@errietta.me>

**Comment by mistohise** [comment]
OK let's close this off for now and re-visit if it becomes a problem.
