### ISSUE TITLE
It should be possible to assign admins via the web front end

### ISSUE THREAD

**Issue by mistohise** [freenode/gms#95]
Please add functionality to manage admins in the web front end

**Comment by errietta** [comment]
Why?

On Wed, Jan 6, 2016, 14:49 Dr Emenculous Paboory <notifications@github.com>
wrote:

> Please add functionality to manage admins in the web front end
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/freenode/gms/issues/95>.
>
-- 
Errietta Kostala
<errietta@errietta.me>

**Comment by mistohise** [comment]
Because where a system is online it should be possible to manage that system without having to resort to another method.  For example, if I am managing groups and want to allow another user to manage groups, I should be able to do that within the system that I'm currently in, and not have to resort to other methods. (specifically, I shouldn't need to SSH somewhere to add an admin, or to see who the list of admins is.)

**Comment by errietta** [comment]
What. Group contacts don't add admins. You can add other GC's through the
site.

On Wed, Jan 6, 2016, 15:21 Dr Emenculous Paboory <notifications@github.com>
wrote:

> Because where a system is online it should be possible to manage that
> system without having to resort to another method. For example, if I am
> managing groups and want to allow another user to manage groups, I should
> be able to do that within the system that I'm currently in, and not have to
> resort to other methods. (specifically, I shouldn't need to SSH somewhere
> to add an admin, or to see who the list of admins is.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/freenode/gms/issues/95#issuecomment-169354057>.
>
-- 
Errietta Kostala
<errietta@errietta.me>

**Comment by mistohise** [comment]
Not for group contacts, for site admins (that is, staff). 
Existing site admins should be able to view and manage admins via the site.

**Comment by decontamin4t0R** [comment]
I'm not a fan of this. A more IRC-stylish thing would be, to add this as a feature to the OperServ...

This would gonna go complicated, though. (Maybe add the gms admin/mod role to the OperServ-Roles, instead of managing it in the own db)

**Comment by mniip** [comment]
As of right now there isn't any backward communication from atheme to GMS. mist is totally right though in that you shouldn't have to ssh into the box to change roles.

**Comment by decontamin4t0R** [comment]
Maybe just do a status symbol behind the username when viewing the user, turning into a button if the current user has the role "useradmin" or something like this? (Would also fix #124 )

**Comment by errietta** [comment]
Done in https://github.com/freenode/gms/commit/75f92c7152e886ce0df92d78a9a330ac1738607a
