### ISSUE TITLE
Add help to gmsserv

### ISSUE THREAD

**Issue by mistohise** [freenode/gms#99]
>gmsserv< help
-GMSServ- Invalid command. Use /msg GMSServ help for a command listing

**Comment by errietta** [comment]
@mistohise There's nothing user-facing in GMSServ. What do you expect the help command to return?

**Comment by mniip** [comment]
[00:11:54] -SaslServ- This service exists to identify connecting clients to the network. It has no public interface.

**Comment by mistohise** [comment]
Something like that, if there's no interface via IRC.  Alternatively, add an interface via IRC to the commands available from the web for staff.

**Comment by mistohise** [comment]
Things that might be useful as user-facing instruments of gmsserv would include a list or count of currently pending actions, and lists of users with gmsserv privs (as in, who can approve groups, etc.) 
But I digress.
